### ISSUE TITLE
Handle the PATH

### ISSUE THREAD

**Issue by LaughingRover** [LaughingRover/simple_shell#10]
Fork must not be called if the command doesn’t exist

**Comment by seunbolt** [comment]
i think the code already handles command lines with arguements

**Comment by LaughingRover** [comment]
Okay, we can handle path then

**Comment by seunbolt** [comment]
definitely, but it seems we are not allowed to use realpath

**Comment by LaughingRover** [comment]
Yes, using the env path will be best. From there we can find if the command exists
